feature/ele 540 support fetching the signing key from a jwks
ttab/elephantine pull request #86
Opened 2024-05-03 13:16 UTC by fred-o

- **WIP**
- **project lead is allergic to changes...**

2024-05-06 07:29 UTC, hugowetterberg commented
PROJECT LEAD IS NOT ALLERGIC TO CHANGES! :wink:

2024-05-06 07:35 UTC, fred-o commented
I blame `git yolo` :)

2024-05-06 07:35 UTC, fred-o commented
Promise I will squash commits properly this time :)

2024-05-06 07:43 UTC, hugowetterberg commented
Awesome! :joy: Apart from the randomly generated bad attitude the PR looks really good so far.
...I wonder how many awkward situations `git yolo` has created for its users.

2024-05-14 13:25 UTC, hugowetterberg requested changes

2024-05-14 13:25 UTC, hugowetterberg commented on go.sum
> +github.com/golang-jwt/jwt/v5 v5.2.0 h1:d/ix8ftRUorsN+5eMIlF4T6J8CAt9rch3My2winC1Jw=
Looks like you need to run a `go mod tidy`

2024-05-14 13:25 UTC, hugowetterberg commented on jwt_test.go
> +	_, _ = parser.AuthInfoFromHeader(fmt.Sprintf("Bearer %s", ss))
What's the point of this last call?

2024-05-14 14:13 UTC, hugowetterberg approved these changes

2024-05-15 07:34 UTC, merged